package com.example.credito_service;

public enum Estado {
    EN_REVISION_INICIAL,
    PENDIENTE_DOCUMENTACION,
    EN_EVALUACION,
    PRE_APROBADA,
    EN_APROBACION_FINAL,
    APROBADA,
    RECHAZADA,
    CANCELADA_POR_CLIENTE,
    EN_DESEMBOLSO
}

